name: Mirror to GitLab

on:
  push:
    branches:
      - master
    tags:
      - "*"    # mirror all tags

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Push to GitLab
        run: |
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "http://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_URL }}"

          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            echo "Pushing branch $BRANCH_NAME to GitLab..."
            git push gitlab HEAD:refs/heads/$BRANCH_NAME
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "Pushing tag $TAG_NAME to GitLab..."
            git push gitlab $TAG_NAME
          fi
