name: Auto Merge After Approval

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types:
      - labeled

jobs:
  merge:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Merge into master
        run: |
          PR_BRANCH=${GITHUB_REF#refs/heads/}
          git fetch origin
          git checkout master
          git pull origin master
          git merge origin/$PR_BRANCH --no-ff -m "Auto-merge $PR_BRANCH into master"
          git push origin master
